# Generated by Django 3.0.7 on 2020-06-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(db_index=True),
        ),
    ]
