# Generated by Django 3.0.7 on 2020-06-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200610_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created_flag',
            field=models.BooleanField(default=True),
        ),
    ]
