# Generated by Django 3.0.5 on 2020-05-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.TextField(db_index=True, default='', unique=True),
        ),
    ]
