# Generated by Django 3.0.7 on 2020-07-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_topic_created_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
