# Generated by Django 3.0.7 on 2020-07-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_topic_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='added_flag',
            field=models.BooleanField(default=True),
        ),
    ]
