"""
Adding start of social login

Revision ID: 258c38620cf0
Revises: 26546376c45e
Create Date: 2020-05-09 11:05:24.024422
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258c38620cf0'
down_revision = '26546376c45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
