# Generated by Django 3.0.5 on 2020-04-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=400)),
            ],
        ),
    ]
